"""
Language definitions for VAANI AI.
Maps display names → deep-translator language codes.
"""

LANGUAGES: dict[str, str] = {
    "Auto Detect":        "auto",
    "Afrikaans":          "af",
    "Albanian":           "sq",
    "Amharic":            "am",
    "Arabic":             "ar",
    "Armenian":           "hy",
    "Azerbaijani":        "az",
    "Basque":             "eu",
    "Belarusian":         "be",
    "Bengali":            "bn",
    "Bosnian":            "bs",
    "Bulgarian":          "bg",
    "Catalan":            "ca",
    "Cebuano":            "ceb",
    "Chichewa":           "ny",
    "Chinese (Simplified)":   "zh-CN",
    "Chinese (Traditional)":  "zh-TW",
    "Corsican":           "co",
    "Croatian":           "hr",
    "Czech":              "cs",
    "Danish":             "da",
    "Dutch":              "nl",
    "English":            "en",
    "Esperanto":          "eo",
    "Estonian":           "et",
    "Filipino":           "tl",
    "Finnish":            "fi",
    "French":             "fr",
    "Frisian":            "fy",
    "Galician":           "gl",
    "Georgian":           "ka",
    "German":             "de",
    "Greek":              "el",
    "Gujarati":           "gu",
    "Haitian Creole":     "ht",
    "Hausa":              "ha",
    "Hawaiian":           "haw",
    "Hebrew":             "iw",
    "Hindi":              "hi",
    "Hmong":              "hmn",
    "Hungarian":          "hu",
    "Icelandic":          "is",
    "Igbo":               "ig",
    "Indonesian":         "id",
    "Irish":              "ga",
    "Italian":            "it",
    "Japanese":           "ja",
    "Javanese":           "jw",
    "Kannada":            "kn",
    "Kazakh":             "kk",
    "Khmer":              "km",
    "Korean":             "ko",
    "Kurdish (Kurmanji)": "ku",
    "Kyrgyz":             "ky",
    "Lao":                "lo",
    "Latin":              "la",
    "Latvian":            "lv",
    "Lithuanian":         "lt",
    "Luxembourgish":      "lb",
    "Macedonian":         "mk",
    "Malagasy":           "mg",
    "Malay":              "ms",
    "Malayalam":          "ml",
    "Maltese":            "mt",
    "Maori":              "mi",
    "Marathi":            "mr",
    "Mongolian":          "mn",
    "Myanmar (Burmese)":  "my",
    "Nepali":             "ne",
    "Norwegian":          "no",
    "Odia (Oriya)":       "or",
    "Pashto":             "ps",
    "Persian":            "fa",
    "Polish":             "pl",
    "Portuguese":         "pt",
    "Punjabi":            "pa",
    "Romanian":           "ro",
    "Russian":            "ru",
    "Samoan":             "sm",
    "Scots Gaelic":       "gd",
    "Serbian":            "sr",
    "Sesotho":            "st",
    "Shona":              "sn",
    "Sindhi":             "sd",
    "Sinhala":            "si",
    "Slovak":             "sk",
    "Slovenian":          "sl",
    "Somali":             "so",
    "Spanish":            "es",
    "Sundanese":          "su",
    "Swahili":            "sw",
    "Swedish":            "sv",
    "Tajik":              "tg",
    "Tamil":              "ta",
    "Telugu":             "te",
    "Thai":               "th",
    "Turkish":            "tr",
    "Ukrainian":          "uk",
    "Urdu":               "ur",
    "Uyghur":             "ug",
    "Uzbek":              "uz",
    "Vietnamese":         "vi",
    "Welsh":              "cy",
    "Xhosa":              "xh",
    "Yiddish":            "yi",
    "Yoruba":             "yo",
    "Zulu":               "zu",
}

ALL_LANGUAGE_NAMES = list(LANGUAGES.keys())
SOURCE_LANGUAGE_NAMES = ALL_LANGUAGE_NAMES                      # includes Auto Detect
TARGET_LANGUAGE_NAMES = [l for l in ALL_LANGUAGE_NAMES if l != "Auto Detect"]

# GTTS language codes (subset that gTTS supports)
GTTS_CODES: dict[str, str] = {
    "af": "af", "ar": "ar", "bn": "bn", "bs": "bs", "ca": "ca",
    "cs": "cs", "cy": "cy", "da": "da", "de": "de", "el": "el",
    "en": "en", "eo": "eo", "es": "es", "et": "et", "fi": "fi",
    "fr": "fr", "gu": "gu", "hi": "hi", "hr": "hr", "hu": "hu",
    "hy": "hy", "id": "id", "is": "is", "it": "it", "ja": "ja",
    "jw": "jw", "km": "km", "kn": "kn", "ko": "ko", "la": "la",
    "lv": "lv", "mk": "mk", "ml": "ml", "mr": "mr", "ms": "ms",
    "my": "my", "ne": "ne", "nl": "nl", "no": "no", "pl": "pl",
    "pt": "pt", "ro": "ro", "ru": "ru", "si": "si", "sk": "sk",
    "sq": "sq", "sr": "sr", "su": "su", "sv": "sv", "sw": "sw",
    "ta": "ta", "te": "te", "th": "th", "tl": "tl", "tr": "tr",
    "uk": "uk", "ur": "ur", "vi": "vi", "zh-CN": "zh-CN", "zh-TW": "zh-TW",
    "iw": "iw",
}
